import { Router } from "express";
import * as c from "../controllers/authController.js";
import { authMiddleware } from "../middleware/authMiddleware.js";
const r = Router();
r.post("/register", c.register);
r.post("/resend-otp", c.resendOtp);
r.post("/verify-otp", c.verifyOtp);
r.post("/set-password", c.setPassword);
r.post("/forgot-password", c.forgotPassword);
r.post("/reset-password", c.resetPassword);
r.post("/login", c.login);
r.post("/logout", c.logout);
r.post("/refresh", authMiddleware, c.refresh);
r.get("/profile", authMiddleware, c.profile);
r.put("/profile", authMiddleware, c.updateProfile);
export default r;
